### ISSUE TITLE
Did not found plugin after following the installation procedure

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [msudgh/terminator-search#3]
Hi there,

Wanted to take a look at your plugin after reading about it [here](https://github.com/k4m4/terminals-are-sexy/pull/137) but could not - I have it in proper path yet it wasn't found.

Any clue what am I not doing or doing wrong?

lafk-T470% ls .config/terminator/plugins 
teminator_search.py
lafk-T470% terminator -v                                                                                                                                                                                  
terminator 1.91
lafk-T470% inxi -S -xxx
System:    Host: lafk-T470 Kernel: 4.15.0-20-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Xfce 4.12.3 (Gtk 2.24.31) info: xfce4-panel dm: lightdm Distro: Ubuntu 18.04 LTS

**Comment by masoudgs** [comment]
Did you enable the plugin and restart `Terminator`?

**Comment by LIttleAncientForestKami** [comment]
I couldn't, plugin window had no Terminator Search, only the default plugins were there. Checked even now.
![terminatornosearchpluginfound_2018-05-07_09-34-33](https://user-images.githubusercontent.com/1167811/39690309-e8ff6876-51d9-11e8-9aca-cae6b0b6a288.png)

**Comment by masoudgs** [comment]
I think it would maybe related to `plugins` directory permission or `Python` version.
Could run `terminator` in `debug` mode by `terminator -d` in another terminal emulator like Ubuntu default terminal and put logs here?

**Comment by LIttleAncientForestKami** [comment]
Debug! Doh, an obvious idea! Sure! Erm, as there's quite the output, I've attached a log.

Are we looking for this? Or should I also look for something else?
`PluginRegistry::prepare_attributes: PluginRegistry::prepare_attributes: Plugin path: ['/usr/share/terminator/terminatorlib/plugins', '/home/tammo/.config/terminator/plugins']
`
Log from an older machine I'm using now [term.log](https://github.com/msudgh/terminator-search/files/1982865/term.log)

I'll add newer machine log as well after I switch to it. 

## Older machine data: 
System:    Host: T420s Kernel: 4.4.0-121-generic x86_64 (64 bit)
           Desktop: Xfce 4.12.3 Distro: Ubuntu 16.04 xenial
terminator 0.98

## Permissions on older machine

![terminatorniemawtyki_2018-05-08_10-11-13](https://user-images.githubusercontent.com/1167811/39745700-4ea084b6-52a8-11e8-8710-94f2e90ea65a.png)

**Comment by masoudgs** [comment]
I read the log file and there wasn't a specific exception about the plugin code, actually, everything was fine. Also, I tried to apply your permission directory and files to my machine and again it works.

Maybe something is wrong with terminator plugin directory. If you look at the log file you'll see that terminator didn't try to load `terminator_search.py` file. I guess by moving plugin file to the main plugin directory it'll work.

Plugin directory on `tammo` machine: `/usr/share/terminator/terminatorlib/plugins`
My Terminator version: `1.91`

**Comment by LIttleAncientForestKami** [comment]
OK, I think I found the problem. Module without attribute "available" on new machine. 
```
PluginRegistry::load_plugins: PluginRegistry::load_plugins: Importing plugin teminator_search.py
PluginRegistry::load_plugins: Importing plugin teminator_search.py failed: 'module' object has no attribute 'AVAILABLE'
```
Full log: 
[newMachine.log](https://github.com/msudgh/terminator-search/files/2020184/newMachine.log)
, for those interested.

Thank you @msudgh for the debug suggestion! 
EDIT: And for plenty of other information, as well as search plug-in. :-)

**Comment by masoudgs** [comment]
Nice try :))
Please change the following line which **`AVAILABLE`** defined to **`available`** in  **`terminator-search.py`**.

https://github.com/msudgh/terminator-search/blob/50c9a4e8ebf24274487d93a54707f254b72d32ac/terminator_search.py#L8

and then restart terminator.
please inform me if it works to fix the bug.

**Comment by LIttleAncientForestKami** [comment]
Actually it is the other way around @msudgh ! I had the lowercase word and I uppercased it. Now it works, though I had to find and quit all instances of terminator (gave me a pause - why the hell are logs from debug that different this time?). I can now search via highlight > right click > choosing search from menu.

Thank you again, both for time spent on this and for work on the plugin. :-)

**Comment by masoudgs** [comment]
Actually, I didn't understand how did you fix it? :D
Which case works? uppercase or lowercase?

**Comment by LIttleAncientForestKami** [comment]
Lowercase was present, uppercase was needed.                                                                                                                                                                         LAFK_PL                                                                                                                                                                            Od: notifications@github.comWysłano: 21 maja 2018 10:44 AMDo: terminator-search@noreply.github.comOdp. do: reply@reply.github.comDW: Tomasz.Borek@gmail.com; state_change@noreply.github.comTemat: Re: [msudgh/terminator-search] Did not found plugin after following the installation procedure (#3)  Actually, I didn't understand how you did fix it :D
Which case works? uppercase or lowercase?
